# Generated by Django 5.2.10 on 2026-01-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_product_petcategory_product_petsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('poultry', 'Poultry'), ('cattle', 'Cattle'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('swine', 'Swine')], max_length=20)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('recommended_age', models.CharField(max_length=100)),
                ('disease_protected', models.TextField()),
                ('booster_required', models.BooleanField(default=False)),
                ('booster_timing', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_revaccination', models.BooleanField(default=False)),
            ],
        ),
    ]
