# Generated by Django 5.2.10 on 2026-01-20 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_vaccine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='adminapp.petsubcategory'),
            preserve_default=False,
        ),
    ]
