# Generated by Django 5.1.3 on 2025-11-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_feedback_user_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
