# Generated by Django 5.1.3 on 2025-11-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('clinical', 'Clinical'), ('audio call', 'Audio Call')], default='clinical', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, choices=[('Vaccine', 'Vaccine'), ('Routine checkup', 'Routine checkup'), ('Sickness', 'Sickness')], max_length=50, null=True),
        ),
    ]
