# Generated by Django 5.1.3 on 2025-11-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('clinical', 'Clinical'), ('audio_call', 'Audio Call')], default='clinical', max_length=20),
        ),
    ]
