# Generated by Django 5.1.3 on 2025-12-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='diagnosis',
            new_name='diagnosis_and_verdict',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='verdict',
        ),
    ]
