# Generated by Django 5.1.3 on 2025-12-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_rename_diagnosis_appointment_diagnosis_and_verdict_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('clinical', 'Clinical'), ('audio_call', 'Audio Call')], max_length=20),
        ),
    ]
