# Generated by Django 5.1.3 on 2025-12-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
