# Generated by Django 5.2.10 on 2026-01-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_appointment_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_for',
            field=models.CharField(choices=[('order', 'Product Order'), ('appointment', 'Doctor Appointment')], default='order', max_length=20),
            preserve_default=False,
        ),
    ]
