# Generated by Django 5.2.10 on 2026-01-19 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_vaccine'),
        ('userapp', '0024_payment_payment_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.vaccine'),
        ),
    ]
