# Generated by Django 5.2.10 on 2026-01-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_appointment_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('poultry', 'Poultry'), ('cattle', 'Cattle'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('swine', 'Swine'), ('other', 'Other')], default='dog', max_length=20),
        ),
    ]
