# Generated by Django 5.2.10 on 2026-01-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_pet_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
