# Generated by Django 5.2.10 on 2026-01-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_alter_appointment_fee_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_type',
        ),
    ]
